github:
  username: JavaRaf                         # Your GitHub username (format: string)
  repo: frames                              # The name of the repo where the episodes which the frames are stored
  branch: main                              # The branch of the repo where the episodes which the frames are stored
  # Example: 
  # javaRafa/
  # └── frames/
  #     └── 01/
  #         ├── frame_0001.jpg
  #         ├── frame_0002.jpg
  #         └── frame_0003.jpg


# progress
in_progress:
  season: 1  # start from 1
  episode: 1 # start from 1
  frame: 11  # start from 0

episodes:
  1:
    image_fps: 3.5   # frames per second of the image/video
    frames: 15       # total frames in the episode
  2:
    image_fps: 3.5   # frames per second of the image/video
    frames: 15       # total frames in the episode
  3:
  4:
  5:
  6:
  7:
  8:
  9:
  10:
  11:
  12:
  13:
  14:
  15:
  16:
  17:
  18:
  19:
  20:
  21:
  22:
  23:
  24:
  25:
  26:
  27:
  28:



posting:
  fph: 15                                  # Frames posted per cicle (format: integer)                            
  posting_interval: 2                      # Interval between posts in minutes (recomended: 2 or more)(format: integer)
  posting_subtitles: true                  # If true, the subtitles will be posted on comments (format: boolean)

  random_crop:                             # Random crop settings
    enabled: true                          # If true, the image will be cropped randomly and posted on comments (format: boolean)
    min_x: 200                             # Minimum crop width (format: integer)
    min_y: 600                             # Minimum crop height (format: integer)

# placeholders:
#   season: The season number
#   episode: The episode number
#   frame: The frame number
#   total_frames: The total frames in the episode
#   timestamp: The timestamp of the frame
#   subtitles: The subtitles of the frame
post_msg: |
  Season {season}, Episode {episode}, Frame {frame} out of {total_frames}
  timestamp: {timestamp}


