name: check variables

on:
  push:
    paths:
      - "subtitles/**"
      - "configs.yml"


jobs:
    check-variables:
        runs-on: ubuntu-latest

        env:
          FB_TOKEN: ${{ secrets.FB_TOKEN }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Set up Python
              uses: actions/setup-python@v5.4.0
              with:
                python-version: "3.13"

            # cache de dependencias
            - name: Cache dependencies
              uses: actions/cache@v4.2.0
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
                  ${{ runner.os }}-

            # instala dependencias
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install -r requirements.txt
                
            - name: Run FB Token Check
              run: |
                python -m src.variable_check